WITH RECURSIVE TIME AS(
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM TIME WHERE H<23
)

SELECT TIME.H AS 'HOUR',
COUNT(A.ANIMAL_ID) AS 'COUNT'
FROM TIME
LEFT JOIN ANIMAL_OUTS A
ON TIME.H = HOUR(A.DATETIME)
GROUP BY TIME.H;
